syntax = "proto3";
package proto;
option go_package = "github.com/Tyulenb/order-kitchen";

service Restaurant {
    rpc CreateOrder(stream OrderDishes) returns (OrderId) {}
    rpc ListOrderStatus(Empty) returns (stream OrderStatusId) {}
    rpc UpdateOrderStatus(OrderId) returns (OrderStatusId) {}
    rpc GetLastOrder(Empty) returns (OrderId) {}
    rpc GetOrderDishes(OrderId) returns (stream OrderDishes) {}
}

message OrderDishes {
    string DishName = 1;
    int32 amount = 2;
}

message OrderId {
    string id = 1;
}

message OrderStatusId {
    string id = 1;
    string status = 2;
}

message OrderStatus {
    string status = 1;
}

message Empty {}
