// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/order-kitchen.proto

package order_kitchen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishName      string                 `protobuf:"bytes,1,opt,name=DishName,proto3" json:"DishName,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_proto_order_kitchen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_kitchen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_kitchen_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetDishName() string {
	if x != nil {
		return x.DishName
	}
	return ""
}

func (x *OrderRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OrderId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderId) Reset() {
	*x = OrderId{}
	mi := &file_proto_order_kitchen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderId) ProtoMessage() {}

func (x *OrderId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_kitchen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderId.ProtoReflect.Descriptor instead.
func (*OrderId) Descriptor() ([]byte, []int) {
	return file_proto_order_kitchen_proto_rawDescGZIP(), []int{1}
}

func (x *OrderId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrderStatusId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusId) Reset() {
	*x = OrderStatusId{}
	mi := &file_proto_order_kitchen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusId) ProtoMessage() {}

func (x *OrderStatusId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_kitchen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusId.ProtoReflect.Descriptor instead.
func (*OrderStatusId) Descriptor() ([]byte, []int) {
	return file_proto_order_kitchen_proto_rawDescGZIP(), []int{2}
}

func (x *OrderStatusId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderStatusId) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_proto_order_kitchen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_kitchen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_proto_order_kitchen_proto_rawDescGZIP(), []int{3}
}

func (x *OrderStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_order_kitchen_proto protoreflect.FileDescriptor

const file_proto_order_kitchen_proto_rawDesc = "" +
	"\n" +
	"\x19proto/order-kitchen.proto\x12\x05proto\"B\n" +
	"\fOrderRequest\x12\x1a\n" +
	"\bDishName\x18\x01 \x01(\tR\bDishName\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"\x19\n" +
	"\aOrderId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\rOrderStatusId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"%\n" +
	"\vOrderStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xb4\x01\n" +
	"\x05Order\x126\n" +
	"\vCreateOrder\x12\x13.proto.OrderRequest\x1a\x0e.proto.OrderId\"\x00(\x01\x126\n" +
	"\x0eGetOrderStatus\x12\x0e.proto.OrderId\x1a\x12.proto.OrderStatus\"\x00\x12;\n" +
	"\x11UpdateOrderStatus\x12\x0e.proto.OrderId\x1a\x14.proto.OrderStatusId\"\x00B\"Z github.com/Tyulenb/order-kitchenb\x06proto3"

var (
	file_proto_order_kitchen_proto_rawDescOnce sync.Once
	file_proto_order_kitchen_proto_rawDescData []byte
)

func file_proto_order_kitchen_proto_rawDescGZIP() []byte {
	file_proto_order_kitchen_proto_rawDescOnce.Do(func() {
		file_proto_order_kitchen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_kitchen_proto_rawDesc), len(file_proto_order_kitchen_proto_rawDesc)))
	})
	return file_proto_order_kitchen_proto_rawDescData
}

var file_proto_order_kitchen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_order_kitchen_proto_goTypes = []any{
	(*OrderRequest)(nil),  // 0: proto.OrderRequest
	(*OrderId)(nil),       // 1: proto.OrderId
	(*OrderStatusId)(nil), // 2: proto.OrderStatusId
	(*OrderStatus)(nil),   // 3: proto.OrderStatus
}
var file_proto_order_kitchen_proto_depIdxs = []int32{
	0, // 0: proto.Order.CreateOrder:input_type -> proto.OrderRequest
	1, // 1: proto.Order.GetOrderStatus:input_type -> proto.OrderId
	1, // 2: proto.Order.UpdateOrderStatus:input_type -> proto.OrderId
	1, // 3: proto.Order.CreateOrder:output_type -> proto.OrderId
	3, // 4: proto.Order.GetOrderStatus:output_type -> proto.OrderStatus
	2, // 5: proto.Order.UpdateOrderStatus:output_type -> proto.OrderStatusId
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_kitchen_proto_init() }
func file_proto_order_kitchen_proto_init() {
	if File_proto_order_kitchen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_kitchen_proto_rawDesc), len(file_proto_order_kitchen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_kitchen_proto_goTypes,
		DependencyIndexes: file_proto_order_kitchen_proto_depIdxs,
		MessageInfos:      file_proto_order_kitchen_proto_msgTypes,
	}.Build()
	File_proto_order_kitchen_proto = out.File
	file_proto_order_kitchen_proto_goTypes = nil
	file_proto_order_kitchen_proto_depIdxs = nil
}
